[workspace]
resolver = "3"
members = ["client", "grpc", "server"]
[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.14"
prost = "0.14"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
