[package]
name = "grpc"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic.workspace = true
prost.workspace = true
prost-types = "0.14"
tonic-prost = "0.14"
validator = "0.20"

[build-dependencies]
tonic-prost-build = "0.14"
